export const APP_STATUS_CHANGE = "APP_STATUS_CHANGE";
export const GRID_ROWS_REQUEST = "GRID_ROWS_REQUEST";
export const GRID_ROWS_RECEIVE_SUCCESS = "GRID_ROWS_RECEIVE_SUCCESS";
export const GRID_ROWS_RECEIVE_FAIL = "GRID_ROWS_RECEIVE_SUCCESS";
export const GRID_STATUS_CHANGE = "GRID_STATUS_CHANGE";
